version: '3'

services:
  api:
    build: .
    command: ./wait-for-it.sh db:5432 -- ./docker-entrypoint.sh
    volumes:
      - ./:/usr/src/app:ro
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:15
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgresdata:/var/lib/postgresql  

volumes:
  postgresdata: