"""Just testing

Revision ID: 50b8a293a04a
Revises: 2664ad524a19
Create Date: 2022-12-29 17:35:27.612464

"""


# revision identifiers, used by Alembic.
revision = "50b8a293a04a"
down_revision = "2664ad524a19"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
