"""Just testing2

Revision ID: dacf118931ff
Revises: 50b8a293a04a
Create Date: 2022-12-29 17:44:23.336583

"""


# revision identifiers, used by Alembic.
revision = "dacf118931ff"
down_revision = "50b8a293a04a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
