"""Autogenerate all tables on main pc

Revision ID: f0a97cfc1a1c
Revises: dacf118931ff
Create Date: 2022-12-29 19:33:34.780397

"""


# revision identifiers, used by Alembic.
revision = "f0a97cfc1a1c"
down_revision = "dacf118931ff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
